### PR TITLE
Material Design and Update to Android Studio

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Hi @SiKni8 ,

I finally found the time to play around with the latest appcompat version and added material design elements to your app. I'm sending you this pull request in case you would like to publish it :)

In order to use this partial rewrite you need to move to Android Studio (I used 1.2 RC), Gradle, the latest Android toolkit and appcompat versions. I also added a German translation.

Screenshot with German translation.

device-2015-04-30-171042
device-2015-04-30-171538

### CODE REVIEW

**Comment by SiKni8** [comment]
Hi Andy

That looks great. I will take a look. Thank you.
If i do republish i will definitely give you credit :)

**Comment by AndyScherzinger** [comment]
Thanks! :) - I already took the liberty of adding me to the credits section ;)

**Comment by SiKni8** [comment]
Awesome. Just saw it. Thanks for helping out.

**Comment by AndyScherzinger** [comment]
You are welcome, it's a pleasure :) 
Am 30.04.2015 21:03 schrieb SiKni8 notifications@github.com:Awesome. Just saw it. Thanks for helping out.

**Comment by SiKni8** [comment]
I was thinking we can collaborate maybe... You know as a team.

**Comment by AndyScherzinger** [comment]
Sure thing ! For me it is the cause behind the idea, that is what I like and support.  It is for the greater good! 
Am 30.04.2015 22:03 schrieb SiKni8 notifications@github.com:I was thinking we can collaborate maybe... You know as a team.

**Comment by SiKni8** [comment]
Please spread the app... This is a great resource to have.

**Comment by SiKni8** [comment]
Hi Andy,

I didn't have a chance to update the app. Is it possible if you already have the code to compile it?

Thanks,
Zahid

**Comment by AndyScherzinger** [comment]
Hi Zahid,
yes I do and it runs on my phone. In case you are asking me to build the APK for a play store release I would need your (private) keystore in ordner to sign it which wouldn't be in your own interest I guess. If you just want me to send you an apk, that can be done right away :)

Andy

**Comment by SiKni8** [comment]
Can you please archive the codes so i can compile and sign it?

**Comment by AndyScherzinger** [comment]
I uploaded a zip to filedropper (might take a while to download)
http://www.filedropper.com/bloodtype_1

I zipped my complete project folder (project is using Android Studio 1.3 RC)

**Comment by AndyScherzinger** [comment]
Any success in compiling / running yet? :)

**Pull request closed without merging**
